# Generated by Django 3.2.2 on 2021-05-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=12, verbose_name='学生id')),
                ('name', models.CharField(max_length=10, verbose_name='学生名称')),
                ('class_room', models.CharField(max_length=50, verbose_name='教室')),
                ('isroom', models.BooleanField(default=False, verbose_name='是否已经验证')),
            ],
        ),
        migrations.CreateModel(
            name='query_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='查询时间')),
                ('picture', models.ImageField(null=True, upload_to='class_img/', verbose_name='班级')),
                ('log', models.CharField(max_length=3000, verbose_name='查询结果')),
                ('class_room', models.CharField(max_length=30, verbose_name='班级')),
            ],
        ),
    ]
